# This is a basic workflow to help you get started with Actions

name: Nuget Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_KEY }}
    - name: Build
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack Kovai.Serverless360.Bam/Kovai.Serverless360.Bam.csproj --output nuget-packages --configuration Release
    - name: Use NuGet.exe
      uses: NuGet/setup-nuget@v1.0.5
      with:
         nuget-api-key: ${{ secrets.NUGET_KEY }}
         nuget-version: '5.x'
    - name: Push
      run: nuget push **/*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{secrets.NUGET_KEY}}
